services:
  mysql_db:
    image: mysql:8.0
    container_name: farmayopin_mysql
    environment:
      MYSQL_DATABASE: farmayopin_db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  mysql_data: